gripper:
#  type: position_controllers/JointTrajectoryController
#  joints:
#     - finger_joint
#  constraints:
#      goal_time: 0.6
#      stopped_velocity_tolerance: 0.05
#      finger_joint: {trajectory: 0.1, goal: 0.1}
#  stop_trajectory_duration: 0.5
#  state_publish_rate:  25
#  action_monitor_rate: 10
  type: effort_controllers/JointPositionController
  joint: finger_joint
  pid: {p: 4.7, i: 0.0, d: 0.2, i_clmap_min: -100.0, i_clamp_max: 100.0}
